apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-con
        image: 450988964435.dkr.ecr.ap-south-1.amazonaws.com/myreopo-github
        ports:
        - containerPort: 80