name: dotnet workflow
on:
  push:
    branches:
      - devolop

jobs: 
  myproject_dotnet:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: project-build
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o pragati
        
# changed
