name: dotnet workflow
on:
  push:
    branches:
      - develop

jobs: 
  myproject_dotnet:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: project-build
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o pragati
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.0.0 # Use the latest stable version
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Your SonarCloud token secret
        with:
          args: >   # >   multiple values
            -Dsonar.organization=pragati029
            -Dsonar.projectKey=pragati029_nopCommerce
            -Dsonar.host.url=https://sonarcloud.io/       
          
