name: dotnet workflow
on:
  push:
    branches:
      - develop

jobs: 
  myproject_dotnet:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: project-build
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o pragati
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3 # Use the latest stable version
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Your SonarCloud token secret
        with:
          args: >   # >   multiple values
            -Dsonar.organization=pragati029
            -Dsonar.projectKey=pragati029_nopCommerce
            -Dsonar.host.url=https://sonarcloud.io/       
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: BuildAndPush
        env:
          ECR_REGISTRY: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 450988964435.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: myreopo-github
          IMAGE_TAG: latest
        run: |    # | multiple values
          docker build -t myreopo-github .
          docker tag myreopo-github:latest 450988964435.dkr.ecr.ap-south-1.amazonaws.com/myreopo-github:latest
          docker push 450988964435.dkr.ecr.ap-south-1.amazonaws.com/myreopo-github:latest
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '450988964435.dkr.ecr.ap-south-1.amazonaws.com/myreopo-github:latest'
          format: 'table'           
          output: 'trivy-results.xml'
          exit-code: '0'          
          ignore-unfixed: true   
          severity: 'CRITICAL,HIGH'
      - name: Update Kubeconfig
        uses: aws-actions/amazon-eks-update-kubeconfig@v3
        with:
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/svc.yaml